<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = array(
            array('id' => 1,'country_code' => 'AF' ,'country_name' => "Afghanistan",'dial_code' => 93),
            array('id' => 2,'country_code' => 'AL' ,'country_name' => "Albania",'dial_code' => 355),
            array('id' => 3,'country_code' => 'DZ' ,'country_name' => "Algeria",'dial_code' => 213),
            array('id' => 4,'country_code' => 'AS' ,'country_name' => "American Samoa",'dial_code' => 1684),
            array('id' => 5,'country_code' => 'AD' ,'country_name' => "Andorra",'dial_code' => 376),
            array('id' => 6,'country_code' => 'AO' ,'country_name' => "Angola",'dial_code' => 244),
            array('id' => 7,'country_code' => 'AI' ,'country_name' => "Anguilla",'dial_code' => 1264),
            array('id' => 8,'country_code' => 'AQ' ,'country_name' => "Antarctica",'dial_code' => 0),
            array('id' => 9,'country_code' => 'AG' ,'country_name' => "Antigua And Barbuda",'dial_code' => 1268),
            array('id' => 10,'country_code' => 'AR','country_name' => "Argentina",'dial_code' => 54),
            array('id' => 11,'country_code' => 'AM','country_name' => "Armenia",'dial_code' => 374),
            array('id' => 12,'country_code' => 'AW','country_name' => "Aruba",'dial_code' => 297),
            array('id' => 13,'country_code' => 'AU','country_name' => "Australia",'dial_code' => 61),
            array('id' => 14,'country_code' => 'AT','country_name' => "Austria",'dial_code' => 43),
            array('id' => 15,'country_code' => 'AZ','country_name' => "Azerbaijan",'dial_code' => 994),
            array('id' => 16,'country_code' => 'BS','country_name' => "Bahamas The",'dial_code' => 1242),
            array('id' => 17,'country_code' => 'BH','country_name' => "Bahrain",'dial_code' => 973),
            array('id' => 18,'country_code' => 'BD','country_name' => "Bangladesh",'dial_code' => 880),
            array('id' => 19,'country_code' => 'BB','country_name' => "Barbados",'dial_code' => 1246),
            array('id' => 20,'country_code' => 'BY','country_name' => "Belarus",'dial_code' => 375),
            array('id' => 21,'country_code' => 'BE','country_name' => "Belgium",'dial_code' => 32),
            array('id' => 22,'country_code' => 'BZ','country_name' => "Belize",'dial_code' => 501),
            array('id' => 23,'country_code' => 'BJ','country_name' => "Benin",'dial_code' => 229),
            array('id' => 24,'country_code' => 'BM','country_name' => "Bermuda",'dial_code' => 1441),
            array('id' => 25,'country_code' => 'BT','country_name' => "Bhutan",'dial_code' => 975),
            array('id' => 26,'country_code' => 'BO','country_name' => "Bolivia",'dial_code' => 591),
            array('id' => 27,'country_code' => 'BA','country_name' => "Bosnia and Herzegovina",'dial_code' => 387),
            array('id' => 28,'country_code' => 'BW','country_name' => "Botswana",'dial_code' => 267),
            array('id' => 29,'country_code' => 'BV','country_name' => "Bouvet Island",'dial_code' => 0),
            array('id' => 30,'country_code' => 'BR','country_name' => "Brazil",'dial_code' => 55),
            array('id' => 31,'country_code' => 'IO','country_name' => "British Indian Ocean Territory",'dial_code' => 246),
            array('id' => 32,'country_code' => 'BN','country_name' => "Brunei",'dial_code' => 673),
            array('id' => 33,'country_code' => 'BG','country_name' => "Bulgaria",'dial_code' => 359),
            array('id' => 34,'country_code' => 'BF','country_name' => "Burkina Faso",'dial_code' => 226),
            array('id' => 35,'country_code' => 'BI','country_name' => "Burundi",'dial_code' => 257),
            array('id' => 36,'country_code' => 'KH','country_name' => "Cambodia",'dial_code' => 855),
            array('id' => 37,'country_code' => 'CM','country_name' => "Cameroon",'dial_code' => 237),
            array('id' => 38,'country_code' => 'CA','country_name' => "Canada",'dial_code' => 1),
            array('id' => 39,'country_code' => 'CV','country_name' => "Cape Verde",'dial_code' => 238),
            array('id' => 40,'country_code' => 'KY','country_name' => "Cayman Islands",'dial_code' => 1345),
            array('id' => 41,'country_code' => 'CF','country_name' => "Central African Republic",'dial_code' => 236),
            array('id' => 42,'country_code' => 'TD','country_name' => "Chad",'dial_code' => 235),
            array('id' => 43,'country_code' => 'CL','country_name' => "Chile",'dial_code' => 56),
            array('id' => 44,'country_code' => 'CN','country_name' => "China",'dial_code' => 86),
            array('id' => 45,'country_code' => 'CX','country_name' => "Christmas Island",'dial_code' => 61),
            array('id' => 46,'country_code' => 'CC','country_name' => "Cocos (Keeling) Islands",'dial_code' => 672),
            array('id' => 47,'country_code' => 'CO','country_name' => "Colombia",'dial_code' => 57),
            array('id' => 48,'country_code' => 'KM','country_name' => "Comoros",'dial_code' => 269),
            array('id' => 49,'country_code' => 'CG','country_name' => "Congo",'dial_code' => 242),
            array('id' => 50,'country_code' => 'CD','country_name' => "Congo The Democratic Republic Of The",'dial_code' => 242),
            array('id' => 51,'country_code' => 'CK','country_name' => "Cook Islands",'dial_code' => 682),
            array('id' => 52,'country_code' => 'CR','country_name' => "Costa Rica",'dial_code' => 506),
            array('id' => 53,'country_code' => 'CI','country_name' => "Cote D Ivoire (Ivory Coast)",'dial_code' => 225),
            array('id' => 54,'country_code' => 'HR','country_name' => "Croatia (Hrvatska)",'dial_code' => 385),
            array('id' => 55,'country_code' => 'CU','country_name' => "Cuba",'dial_code' => 53),
            array('id' => 56,'country_code' => 'CY','country_name' => "Cyprus",'dial_code' => 357),
            array('id' => 57,'country_code' => 'CZ','country_name' => "Czech Republic",'dial_code' => 420),
            array('id' => 58,'country_code' => 'DK','country_name' => "Denmark",'dial_code' => 45),
            array('id' => 59,'country_code' => 'DJ','country_name' => "Djibouti",'dial_code' => 253),
            array('id' => 60,'country_code' => 'DM','country_name' => "Dominica",'dial_code' => 1767),
            array('id' => 61,'country_code' => 'DO','country_name' => "Dominican Republic",'dial_code' => 1809),
            array('id' => 62,'country_code' => 'TP','country_name' => "East Timor",'dial_code' => 670),
            array('id' => 63,'country_code' => 'EC','country_name' => "Ecuador",'dial_code' => 593),
            array('id' => 64,'country_code' => 'EG','country_name' => "Egypt",'dial_code' => 20),
            array('id' => 65,'country_code' => 'SV','country_name' => "El Salvador",'dial_code' => 503),
            array('id' => 66,'country_code' => 'GQ','country_name' => "Equatorial Guinea",'dial_code' => 240),
            array('id' => 67,'country_code' => 'ER','country_name' => "Eritrea",'dial_code' => 291),
            array('id' => 68,'country_code' => 'EE','country_name' => "Estonia",'dial_code' => 372),
            array('id' => 69,'country_code' => 'ET','country_name' => "Ethiopia",'dial_code' => 251),
            array('id' => 70,'country_code' => 'XA','country_name' => "External Territories of Australia",'dial_code' => 61),
            array('id' => 71,'country_code' => 'FK','country_name' => "Falkland Islands",'dial_code' => 500),
            array('id' => 72,'country_code' => 'FO','country_name' => "Faroe Islands",'dial_code' => 298),
            array('id' => 73,'country_code' => 'FJ','country_name' => "Fiji Islands",'dial_code' => 679),
            array('id' => 74,'country_code' => 'FI','country_name' => "Finland",'dial_code' => 358),
            array('id' => 75,'country_code' => 'FR','country_name' => "France",'dial_code' => 33),
            array('id' => 76,'country_code' => 'GF','country_name' => "French Guiana",'dial_code' => 594),
            array('id' => 77,'country_code' => 'PF','country_name' => "French Polynesia",'dial_code' => 689),
            array('id' => 78,'country_code' => 'TF','country_name' => "French Southern Territories",'dial_code' => 0),
            array('id' => 79,'country_code' => 'GA','country_name' => "Gabon",'dial_code' => 241),
            array('id' => 80,'country_code' => 'GM','country_name' => "Gambia The",'dial_code' => 220),
            array('id' => 81,'country_code' => 'GE','country_name' => "Georgia",'dial_code' => 995),
            array('id' => 82,'country_code' => 'DE','country_name' => "Germany",'dial_code' => 49),
            array('id' => 83,'country_code' => 'GH','country_name' => "Ghana",'dial_code' => 233),
            array('id' => 84,'country_code' => 'GI','country_name' => "Gibraltar",'dial_code' => 350),
            array('id' => 85,'country_code' => 'GR','country_name' => "Greece",'dial_code' => 30),
            array('id' => 86,'country_code' => 'GL','country_name' => "Greenland",'dial_code' => 299),
            array('id' => 87,'country_code' => 'GD','country_name' => "Grenada",'dial_code' => 1473),
            array('id' => 88,'country_code' => 'GP','country_name' => "Guadeloupe",'dial_code' => 590),
            array('id' => 89,'country_code' => 'GU','country_name' => "Guam",'dial_code' => 1671),
            array('id' => 90,'country_code' => 'GT','country_name' => "Guatemala",'dial_code' => 502),
            array('id' => 91,'country_code' => 'XU','country_name' => "Guernsey and Alderney",'dial_code' => 44),
            array('id' => 92,'country_code' => 'GN','country_name' => "Guinea",'dial_code' => 224),
            array('id' => 93,'country_code' => 'GW','country_name' => "Guinea-Bissau",'dial_code' => 245),
            array('id' => 94,'country_code' => 'GY','country_name' => "Guyana",'dial_code' => 592),
            array('id' => 95,'country_code' => 'HT','country_name' => "Haiti",'dial_code' => 509),
            array('id' => 96,'country_code' => 'HM','country_name' => "Heard and McDonald Islands",'dial_code' => 0),
            array('id' => 97,'country_code' => 'HN','country_name' => "Honduras",'dial_code' => 504),
            array('id' => 98,'country_code' => 'HK','country_name' => "Hong Kong S.A.R.",'dial_code' => 852),
            array('id' => 99,'country_code' => 'HU','country_name' => "Hungary",'dial_code' => 36),
            array('id' => 100,'country_code' => 'IS','country_name' => "Iceland",'dial_code' => 354),
            array('id' => 101,'country_code' => 'IN','country_name' => "India",'dial_code' => 91),
            array('id' => 102,'country_code' => 'ID','country_name' => "Indonesia",'dial_code' => 62),
            array('id' => 103,'country_code' => 'IR','country_name' => "Iran",'dial_code' => 98),
            array('id' => 104,'country_code' => 'IQ','country_name' => "Iraq",'dial_code' => 964),
            array('id' => 105,'country_code' => 'IE','country_name' => "Ireland",'dial_code' => 353),
            array('id' => 106,'country_code' => 'IL','country_name' => "Israel",'dial_code' => 972),
            array('id' => 107,'country_code' => 'IT','country_name' => "Italy",'dial_code' => 39),
            array('id' => 108,'country_code' => 'JM','country_name' => "Jamaica",'dial_code' => 1876),
            array('id' => 109,'country_code' => 'JP','country_name' => "Japan",'dial_code' => 81),
            array('id' => 110,'country_code' => 'XJ','country_name' => "Jersey",'dial_code' => 44),
            array('id' => 111,'country_code' => 'JO','country_name' => "Jordan",'dial_code' => 962),
            array('id' => 112,'country_code' => 'KZ','country_name' => "Kazakhstan",'dial_code' => 7),
            array('id' => 113,'country_code' => 'KE','country_name' => "Kenya",'dial_code' => 254),
            array('id' => 114,'country_code' => 'KI','country_name' => "Kiribati",'dial_code' => 686),
            array('id' => 115,'country_code' => 'KP','country_name' => "Korea North",'dial_code' => 850),
            array('id' => 116,'country_code' => 'KR','country_name' => "Korea South",'dial_code' => 82),
            array('id' => 117,'country_code' => 'KW','country_name' => "Kuwait",'dial_code' => 965),
            array('id' => 118,'country_code' => 'KG','country_name' => "Kyrgyzstan",'dial_code' => 996),
            array('id' => 119,'country_code' => 'LA','country_name' => "Laos",'dial_code' => 856),
            array('id' => 120,'country_code' => 'LV','country_name' => "Latvia",'dial_code' => 371),
            array('id' => 121,'country_code' => 'LB','country_name' => "Lebanon",'dial_code' => 961),
            array('id' => 122,'country_code' => 'LS','country_name' => "Lesotho",'dial_code' => 266),
            array('id' => 123,'country_code' => 'LR','country_name' => "Liberia",'dial_code' => 231),
            array('id' => 124,'country_code' => 'LY','country_name' => "Libya",'dial_code' => 218),
            array('id' => 125,'country_code' => 'LI','country_name' => "Liechtenstein",'dial_code' => 423),
            array('id' => 126,'country_code' => 'LT','country_name' => "Lithuania",'dial_code' => 370),
            array('id' => 127,'country_code' => 'LU','country_name' => "Luxembourg",'dial_code' => 352),
            array('id' => 128,'country_code' => 'MO','country_name' => "Macau S.A.R.",'dial_code' => 853),
            array('id' => 129,'country_code' => 'MK','country_name' => "Macedonia",'dial_code' => 389),
            array('id' => 130,'country_code' => 'MG','country_name' => "Madagascar",'dial_code' => 261),
            array('id' => 131,'country_code' => 'MW','country_name' => "Malawi",'dial_code' => 265),
            array('id' => 132,'country_code' => 'MY','country_name' => "Malaysia",'dial_code' => 60),
            array('id' => 133,'country_code' => 'MV','country_name' => "Maldives",'dial_code' => 960),
            array('id' => 134,'country_code' => 'ML','country_name' => "Mali",'dial_code' => 223),
            array('id' => 135,'country_code' => 'MT','country_name' => "Malta",'dial_code' => 356),
            array('id' => 136,'country_code' => 'XM','country_name' => "Man (Isle of)",'dial_code' => 44),
            array('id' => 137,'country_code' => 'MH','country_name' => "Marshall Islands",'dial_code' => 692),
            array('id' => 138,'country_code' => 'MQ','country_name' => "Martinique",'dial_code' => 596),
            array('id' => 139,'country_code' => 'MR','country_name' => "Mauritania",'dial_code' => 222),
            array('id' => 140,'country_code' => 'MU','country_name' => "Mauritius",'dial_code' => 230),
            array('id' => 141,'country_code' => 'YT','country_name' => "Mayotte",'dial_code' => 269),
            array('id' => 142,'country_code' => 'MX','country_name' => "Mexico",'dial_code' => 52),
            array('id' => 143,'country_code' => 'FM','country_name' => "Micronesia",'dial_code' => 691),
            array('id' => 144,'country_code' => 'MD','country_name' => "Moldova",'dial_code' => 373),
            array('id' => 145,'country_code' => 'MC','country_name' => "Monaco",'dial_code' => 377),
            array('id' => 146,'country_code' => 'MN','country_name' => "Mongolia",'dial_code' => 976),
            array('id' => 147,'country_code' => 'MS','country_name' => "Montserrat",'dial_code' => 1664),
            array('id' => 148,'country_code' => 'MA','country_name' => "Morocco",'dial_code' => 212),
            array('id' => 149,'country_code' => 'MZ','country_name' => "Mozambique",'dial_code' => 258),
            array('id' => 150,'country_code' => 'MM','country_name' => "Myanmar",'dial_code' => 95),
            array('id' => 151,'country_code' => 'NA','country_name' => "Namibia",'dial_code' => 264),
            array('id' => 152,'country_code' => 'NR','country_name' => "Nauru",'dial_code' => 674),
            array('id' => 153,'country_code' => 'NP','country_name' => "Nepal",'dial_code' => 977),
            array('id' => 154,'country_code' => 'AN','country_name' => "Netherlands Antilles",'dial_code' => 599),
            array('id' => 155,'country_code' => 'NL','country_name' => "Netherlands The",'dial_code' => 31),
            array('id' => 156,'country_code' => 'NC','country_name' => "New Caledonia",'dial_code' => 687),
            array('id' => 157,'country_code' => 'NZ','country_name' => "New Zealand",'dial_code' => 64),
            array('id' => 158,'country_code' => 'NI','country_name' => "Nicaragua",'dial_code' => 505),
            array('id' => 159,'country_code' => 'NE','country_name' => "Niger",'dial_code' => 227),
            array('id' => 160,'country_code' => 'NG','country_name' => "Nigeria",'dial_code' => 234),
            array('id' => 161,'country_code' => 'NU','country_name' => "Niue",'dial_code' => 683),
            array('id' => 162,'country_code' => 'NF','country_name' => "Norfolk Island",'dial_code' => 672),
            array('id' => 163,'country_code' => 'MP','country_name' => "Northern Mariana Islands",'dial_code' => 1670),
            array('id' => 164,'country_code' => 'NO','country_name' => "Norway",'dial_code' => 47),
            array('id' => 165,'country_code' => 'OM','country_name' => "Oman",'dial_code' => 968),
            array('id' => 166,'country_code' => 'PK','country_name' => "Pakistan",'dial_code' => 92),
            array('id' => 167,'country_code' => 'PW','country_name' => "Palau",'dial_code' => 680),
            array('id' => 168,'country_code' => 'PS','country_name' => "Palestinian Territory Occupied",'dial_code' => 970),
            array('id' => 169,'country_code' => 'PA','country_name' => "Panama",'dial_code' => 507),
            array('id' => 170,'country_code' => 'PG','country_name' => "Papua new Guinea",'dial_code' => 675),
            array('id' => 171,'country_code' => 'PY','country_name' => "Paraguay",'dial_code' => 595),
            array('id' => 172,'country_code' => 'PE','country_name' => "Peru",'dial_code' => 51),
            array('id' => 173,'country_code' => 'PH','country_name' => "Philippines",'dial_code' => 63),
            array('id' => 174,'country_code' => 'PN','country_name' => "Pitcairn Island",'dial_code' => 0),
            array('id' => 175,'country_code' => 'PL','country_name' => "Poland",'dial_code' => 48),
            array('id' => 176,'country_code' => 'PT','country_name' => "Portugal",'dial_code' => 351),
            array('id' => 177,'country_code' => 'PR','country_name' => "Puerto Rico",'dial_code' => 1787),
            array('id' => 178,'country_code' => 'QA','country_name' => "Qatar",'dial_code' => 974),
            array('id' => 179,'country_code' => 'RE','country_name' => "Reunion",'dial_code' => 262),
            array('id' => 180,'country_code' => 'RO','country_name' => "Romania",'dial_code' => 40),
            array('id' => 181,'country_code' => 'RU','country_name' => "Russia",'dial_code' => 70),
            array('id' => 182,'country_code' => 'RW','country_name' => "Rwanda",'dial_code' => 250),
            array('id' => 183,'country_code' => 'SH','country_name' => "Saint Helena",'dial_code' => 290),
            array('id' => 184,'country_code' => 'KN','country_name' => "Saint Kitts And Nevis",'dial_code' => 1869),
            array('id' => 185,'country_code' => 'LC','country_name' => "Saint Lucia",'dial_code' => 1758),
            array('id' => 186,'country_code' => 'PM','country_name' => "Saint Pierre and Miquelon",'dial_code' => 508),
            array('id' => 187,'country_code' => 'VC','country_name' => "Saint Vincent And The Grenadines",'dial_code' => 1784),
            array('id' => 188,'country_code' => 'WS','country_name' => "Samoa",'dial_code' => 684),
            array('id' => 189,'country_code' => 'SM','country_name' => "San Marino",'dial_code' => 378),
            array('id' => 190,'country_code' => 'ST','country_name' => "Sao Tome and Principe",'dial_code' => 239),
            array('id' => 191,'country_code' => 'SA','country_name' => "Saudi Arabia",'dial_code' => 966),
            array('id' => 192,'country_code' => 'SN','country_name' => "Senegal",'dial_code' => 221),
            array('id' => 193,'country_code' => 'RS','country_name' => "Serbia",'dial_code' => 381),
            array('id' => 194,'country_code' => 'SC','country_name' => "Seychelles",'dial_code' => 248),
            array('id' => 195,'country_code' => 'SL','country_name' => "Sierra Leone",'dial_code' => 232),
            array('id' => 196,'country_code' => 'SG','country_name' => "Singapore",'dial_code' => 65),
            array('id' => 197,'country_code' => 'SK','country_name' => "Slovakia",'dial_code' => 421),
            array('id' => 198,'country_code' => 'SI','country_name' => "Slovenia",'dial_code' => 386),
            array('id' => 199,'country_code' => 'XG','country_name' => "Smaller Territories of the UK",'dial_code' => 44),
            array('id' => 200,'country_code' => 'SB','country_name' => "Solomon Islands",'dial_code' => 677),
            array('id' => 201,'country_code' => 'SO','country_name' => "Somalia",'dial_code' => 252),
            array('id' => 202,'country_code' => 'ZA','country_name' => "South Africa",'dial_code' => 27),
            array('id' => 203,'country_code' => 'GS','country_name' => "South Georgia",'dial_code' => 0),
            array('id' => 204,'country_code' => 'SS','country_name' => "South Sudan",'dial_code' => 211),
            array('id' => 205,'country_code' => 'ES','country_name' => "Spain",'dial_code' => 34),
            array('id' => 206,'country_code' => 'LK','country_name' => "Sri Lanka",'dial_code' => 94),
            array('id' => 207,'country_code' => 'SD','country_name' => "Sudan",'dial_code' => 249),
            array('id' => 208,'country_code' => 'SR','country_name' => "Suriname",'dial_code' => 597),
            array('id' => 209,'country_code' => 'SJ','country_name' => "Svalbard And Jan Mayen Islands",'dial_code' => 47),
            array('id' => 210,'country_code' => 'SZ','country_name' => "Swaziland",'dial_code' => 268),
            array('id' => 211,'country_code' => 'SE','country_name' => "Sweden",'dial_code' => 46),
            array('id' => 212,'country_code' => 'CH','country_name' => "Switzerland",'dial_code' => 41),
            array('id' => 213,'country_code' => 'SY','country_name' => "Syria",'dial_code' => 963),
            array('id' => 214,'country_code' => 'TW','country_name' => "Taiwan",'dial_code' => 886),
            array('id' => 215,'country_code' => 'TJ','country_name' => "Tajikistan",'dial_code' => 992),
            array('id' => 216,'country_code' => 'TZ','country_name' => "Tanzania",'dial_code' => 255),
            array('id' => 217,'country_code' => 'TH','country_name' => "Thailand",'dial_code' => 66),
            array('id' => 218,'country_code' => 'TG','country_name' => "Togo",'dial_code' => 228),
            array('id' => 219,'country_code' => 'TK','country_name' => "Tokelau",'dial_code' => 690),
            array('id' => 220,'country_code' => 'TO','country_name' => "Tonga",'dial_code' => 676),
            array('id' => 221,'country_code' => 'TT','country_name' => "Trinidad And Tobago",'dial_code' => 1868),
            array('id' => 222,'country_code' => 'TN','country_name' => "Tunisia",'dial_code' => 216),
            array('id' => 223,'country_code' => 'TR','country_name' => "Turkey",'dial_code' => 90),
            array('id' => 224,'country_code' => 'TM','country_name' => "Turkmenistan",'dial_code' => 7370),
            array('id' => 225,'country_code' => 'TC','country_name' => "Turks And Caicos Islands",'dial_code' => 1649),
            array('id' => 226,'country_code' => 'TV','country_name' => "Tuvalu",'dial_code' => 688),
            array('id' => 227,'country_code' => 'UG','country_name' => "Uganda",'dial_code' => 256),
            array('id' => 228,'country_code' => 'UA','country_name' => "Ukraine",'dial_code' => 380),
            array('id' => 229,'country_code' => 'AE','country_name' => "United Arab Emirates",'dial_code' => 971),
            array('id' => 230,'country_code' => 'GB','country_name' => "United Kingdom",'dial_code' => 44),
            array('id' => 231,'country_code' => 'US','country_name' => "United States",'dial_code' => 1),
            array('id' => 232,'country_code' => 'UM','country_name' => "United States Minor Outlying Islands",'dial_code' => 1),
            array('id' => 233,'country_code' => 'UY','country_name' => "Uruguay",'dial_code' => 598),
            array('id' => 234,'country_code' => 'UZ','country_name' => "Uzbekistan",'dial_code' => 998),
            array('id' => 235,'country_code' => 'VU','country_name' => "Vanuatu",'dial_code' => 678),
            array('id' => 236,'country_code' => 'VA','country_name' => "Vatican City State (Holy See)",'dial_code' => 39),
            array('id' => 237,'country_code' => 'VE','country_name' => "Venezuela",'dial_code' => 58),
            array('id' => 238,'country_code' => 'VN','country_name' => "Vietnam",'dial_code' => 84),
            array('id' => 239,'country_code' => 'VG','country_name' => "Virgin Islands (British)",'dial_code' => 1284),
            array('id' => 240,'country_code' => 'VI','country_name' => "Virgin Islands (US)",'dial_code' => 1340),
            array('id' => 241,'country_code' => 'WF','country_name' => "Wallis And Futuna Islands",'dial_code' => 681),
            array('id' => 242,'country_code' => 'EH','country_name' => "Western Sahara",'dial_code' => 212),
            array('id' => 243,'country_code' => 'YE','country_name' => "Yemen",'dial_code' => 967),
            array('id' => 244,'country_code' => 'YU','country_name' => "Yugoslavia",'dial_code' => 38),
            array('id' => 245,'country_code' => 'ZM','country_name' => "Zambia",'dial_code' => 260),
            array('id' => 246,'country_code' => 'ZW','country_name' => "Zimbabwe",'dial_code' => 263),
        );

        foreach($countries as $key => $country){
            $country['slug'] = str_replace(' ', '-', strtolower($country['country_name']));
            $countries[$key] = $country;
        }

        $country = Country::count();
        if($country == 0) {
            DB::table('countries')->insert($countries);
        }
    }
}
